### ISSUE TITLE
Advanced search is not supported by twitteR

### ISSUE THREAD

**Issue by Horopter** [geoffjentry/twitteR#102]
I want to perform custom search as searchTwitter('#Dabangg', n = 16000, since = "2012-04-29 IST", until = "2015-09-20 IST"). However, this package is not supporting two things in general.
1. I want a set of tweets in a span of an year, the default 1500 isn't gonna do that for me.
2. Advanced search in this package still goes as far as say 8 days back at the most. Is there a way I can use a bigger timeframe?

**Comment by igorbrigadir** [comment]
Unfortunately you can't use the API to request tweets older than a week or two at most. This is a restriction of the Twitter Search API.

**Comment by geoffjentry** [comment]
As noted by commenter, the date limitations are from the API and there's nothing the package can do to get around that
