### ISSUE TITLE
retweet a tweet with twitteR

### ISSUE THREAD

**Issue by yrochat** [geoffjentry/twitteR#103]
Dear Jeff,

I would enjoy using such a function within your package for a twitterbot project. Do you think that it is conceivable?

I think that the corresponding API entry is https://dev.twitter.com/rest/reference/post/statuses/retweet/%3Aid

Thanks again for this great package!

Best,

Yannick

**Comment by Kevin-Brosnan** [comment]
I too was interested in such a function. I have added a function retweetStatus to my version of twitteR which allows such functionality. The code for this is below. Feel free to use. 

retweetStatus <- function(status, ...){
  if (!has_oauth_token()) {
    stop("retweetStatus requires OAuth authentication")
  }
  if (!inherits(status, 'status')) {
    stop("status argument must be of class status")
  }
  
  json = twInterfaceObj$doAPICall(paste('statuses/retweet',
                                        status$getId(), sep='/'),
                                  method='POST', ...)
  if (is.null(json$errors)) {
    return(TRUE)
  } else {
    for (error in json$errors) {
      cat(error$message, error$code, fill = TRUE)
    }
    return(FALSE)
  }
}

**Comment by yrochat** [comment]
Dear Kevin,

Thank you for your answer! It took me > 1 hour to make it work, but I've learned tons of things incidentally. Wouldn't you want to submit a pull request?

**If anybody passes by and needs to know how to make it work, please find the instructions below.** If you don't care, simply execute ```install_github("yrochat/twitteR")```

1. fork twitteR https://github.com/geoffjentry/twitteR
2. in the forked repository, copy the function given by Kevin above and paste it at the end of this file ```https://github.com/your_username/twitteR/blob/master/R/statuses.R```
3. in the forked repository, add the function ```retweetStatus``` to the ```NAMESPACE``` file so that it is not *private* anymore ```https://github.com/your_username/twitteR/blob/master/NAMESPACE```
4. install your forked version in R: ```install_github("your_username/twitteR")``` It will replace the previous one.
