### ISSUE TITLE
Error in check_twitter_oauth() : OAuth authentication error: (again)

### ISSUE THREAD

**Issue by Stazzyman** [geoffjentry/twitteR#109]
Hello,

Sorry to bring up this issue yet again but I'm still getting the same old Oauth error. Here's my sessionInfo():
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] base64enc_0.1-3 twitteR_1.1.9   devtools_1.9.1 

loaded via a namespace (and not attached):
 [1] bit_1.1-12      httr_1.0.0.9000 rjson_0.2.15    R6_2.1.1        DBI_0.3.1       curl_0.9.4      memoise_0.2.1  
 [8] bit64_0.9-5     digest_0.6.9    openssl_0.8    

Then when I run the setup_twitter_oauth() code I get the following:

> setup_twitter_oauth(consumer_key,consumer_secret,access_token,access_key)
[1] "Using direct authentication"
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: 2
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

Hopefully you can see that I've installed the latest base64enc, and have got the latest versions of twitteR and httr. If anyone has any suggestions I'd be really grateful!

Sam

**Comment by bfontana** [comment]
Same Here. Perhaps an issue with "El Capitan"?

> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] twitteR_1.1.9

loaded via a namespace (and not attached):
 [1] bit_1.1-12      httr_1.0.0      rjson_0.2.15    R6_2.1.2       
 [5] magrittr_1.5    DBI_0.3.1       tools_3.2.4     base64enc_0.1-3
 [9] curl_0.9.6      bit64_0.9-5     stringi_1.0-1   digest_0.6.9   
[13] stringr_1.0.0

**Comment by bfontana** [comment]
I tried in Linux CentOS 6.6 with CRAN twitteR version (twitter_1.1.9)  and it worked like a charm. I've noted that bit64 was not installed on OSX. I installed it and retried on OSX but still getting error. So I compared libraries and openssl and curl where not automagically loaded when twitteR is load. Loading them manually finally worked!!

library("curl")
library("openssl")
library("twitteR")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)

**Comment by bfontana** [comment]
Well seems not a problem with R itself but with "R for Mac OS X GUI" (GUI started from Applications). From console command-line it worked fine. Any clues?

**Comment by geoffjentry** [comment]
I'm not able to replicate this on El Capitan using console nor rstudio - I don't use the mac gui. I'd try to use Hadley's httr twitter example and if that doesn't work talk to him. setup_twitter_oauth is really just a thin wrapper around httr code so it's likely a weird interplay there.
