### ISSUE TITLE
Authentication over shinyapps.io

### ISSUE THREAD

**Issue by debsush** [geoffjentry/twitteR#120]
Hi,

I have a webapp in shinyapps.io  Currently, shinyapps.io does not permit the port 1410 and hence I would like to know if there is a way by which I can have the users to my webapp authenticate using their twitteR authentication process flow over shinyapps.io and then call some of the APIs to perform a task.  

Also, is it possible to use the APIs to post/tweet some content (or link) to the users respective twitter account?

I am relatively new to the world of APIs and servers and so please excuse my ignorance.

Thank you
SD

**Comment by geoffjentry** [comment]
I honestly have no idea about anything regarding shinyapps.io - unfortunately I've used R roughly 1-2 times per year for the last 4-5 years so I'm pretty out of touch.

You can use twitteR to tweet. Look at the `tweet` function. You'll need to be authenticated via oauth as that user however.

Rereading your full question my rough guess is that it'll likely be tough to do what you want to do, but I really don't know. You might want to talk to Hadley about handling oauth based connections in general with the sort of scheme you want - if/when that can be made to work I have a feeling that twitteR isn't (yet) flexible to handle things in a reasonable fashion but one thing at a time.
