### ISSUE TITLE
‘TwittR’ is not available (for R version 3.3.0)

### ISSUE THREAD

**Issue by andrewbcooper** [geoffjentry/twitteR#121]
Hello!  Thank you for writing such a great package!  For better or worse, at my new job, they're running R v3.3.0.  When i tried to install TwittR, I got the warning: ‘TwittR’ is not available (for R version 3.3.0).  Do you happen to know any way around this?  Thanks!

**Comment by omriduek** [comment]
Me too... should still work since it's a warning, not error, unless you're
having other issues.

**Comment by kkumars** [comment]
Please check spelling mistake of TwitteR

**Comment by andrewbcooper** [comment]
Thanks, @kkumars!  I'm an idiot!

**Comment by geoffjentry** [comment]
Looks like all is well in the world :)
