### ISSUE TITLE
issue with amount of returned data for calls

### ISSUE THREAD

**Issue by ghonk** [geoffjentry/twitteR#125]
first thanks for the great package

I have been using this for a class I teach and have found that it does not return a comprehensive set of the thing I'm searching for. I'm hoping this is just an issue with the class parameters

to clarify, I follow my students, but this call only returns 9 of them (rather than 12)
```
user_profhonk <- getUser('profHonk')
lapply(user_profhonk$getFriends(n = NULL), function(x) x$screenName)

```

another example, the students submit assignments with hashtags, but I just found that this call missed at least one of their submissions
```

cpt1_5 <- searchTwitter('#cpt1_5') # p-hacking
ppl_to_credit_cpt1_5 <- 
  cbind(cpt1_5 = .5, sn = unique(unlist(lapply(cpt1_5, function(x) x$screenName))))
```

Hoping I'm just initiating these calls wrong. Thanks for any possible advice and let me know if you need more information

**Comment by geoffjentry** [comment]
Hi - I just pushed a change to fix this. The package is showing its age, those missing folks had IDs too large to fit in a numeric and I needed to update against the newer API option to get the IDs back as strings
