### ISSUE TITLE
showStatus and lookup_statuses return error

### ISSUE THREAD

**Issue by kurtawirth** [geoffjentry/twitteR#150]
When using either of these with any ID, such as "1090325128196603905", I get the following error:

`Error: $ operator is invalid for atomic vectors`

The code is simply:

`test <- showStatus("1090325128196603905")`

My oath seems to be working fine; any ideas?

**Comment by kurtawirth** [comment]
Correction; it seems my oath isn't working after all. Will update.

**Comment by kurtawirth** [comment]
Can't figure out how to use the oath thing. Will close now.

**Comment by BroVic** [comment]
Do you know how to use OAuth in general?

**Comment by kurtawirth** [comment]
I had missed the function built in to use oath. It's working now. Sorry for
the confusion.
