### ISSUE TITLE
setup_twitter_oauth documentation missing

### ISSUE THREAD

**Issue by AugustT** [geoffjentry/twitteR#42]
using the function registerTwitterOAuth(Cred)

produces the error:

Error in registerTwitterOAuth(Cred) : 
  ROAuth is no longer used in favor of httr, please see ?setup_twitter_oauth

but no such documentation exists

**Comment by ruscello** [comment]
I can't solve same problem,too.
How do you be resolved I do?

**Comment by geoffjentry** [comment]
@ruscello You shouldn't be having any problems involving ROAuth, the package doesn't use it any longer

**Comment by pratipsen** [comment]
Hi Geoff - I recently updated to twitteR 1.1.8. And calling the package has become incredibly difficult than what it was with the earlier version 1.1.7.
My apps were working fine in previous version and now I have no clue as to what is happening! Neither there is an authentic method nor are th packages always compatible (such as httr). 
I keep on getting error msgs like:
--- 
Error in setup_twitter_oauth(consumerKey, consumerSecret, access_token,  : 
  unused argument (credentials_file = NULL)
---
> setup_twitter_oauth(consumerKey, consumerSecret, access_token, access_token_secret)
[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

---

> twitter_token <- oauth1.0_token(oauth_endpoints("twitter"), myapp)
Use a local file to cache OAuth access credentials between R sessions?
1: Yes
2: No

Selection: req <- GET("https://api.twitter.com/1.1/statuses/home_timeline.json",config(token = twitter_token))
Enter an item from the menu, or 0 to exit
Selection: stop_for_status(req)
Enter an item from the menu, or 0 to exit
Selection: content(req)2
Enter an item from the menu, or 0 to exit
Selection: 0
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission) : 
  client error: (401) Unauthorized
----

Can you help us with a standard writeup of connectivity including packages to be installed?

Thanks,
Insane

**Comment by geoffjentry** [comment]
Hi @pratipsen 

Try running the code manually from https://github.com/hadley/httr/blob/master/demo/oauth1-twitter.r (it looks like you might have already done that).

If that's not working for you, the problem exists between yourself and the httr package and you should talk to Hadley. Most of the time people when people say they have problems it sounds like they're behind a firewall or something like that.

If you can get that demo consistently working but not the authentication via twitteR, let me know, that's not something which I've encountered.
