### ISSUE TITLE
List of Followers

### ISSUE THREAD

**Issue by mcheney100** [geoffjentry/twitteR#56]
Hey Geoff, 

Im a R novice so excuse my general ignorance. Im trying to get a list of followers for a particular twitter user. The code here is not working for me. Im getting error code "could not find function ffbase". Say Im trying to download a list of Barack Obama's followers. How could I do that? 

Also - Is it possible to get a list of geo-located followers? 

thanks x 1 mil!!

**Comment by geoffjentry** [comment]
This is > 2 years old, and I've never seen this error. On the off chance you're still wondering about this and if you can replicate it, submit a new issue w/ code to replicate.
