### ISSUE TITLE
Error in check_twitter_oauth() : OAuth authentication error:

### ISSUE THREAD

**Issue by llZeroll** [geoffjentry/twitteR#67]
Hello everybody 

i have this problem in my code 

install.packages(c("devtools", "rjson", "bit64", "httr"))
devtools::install_github("hadley/httr")
# RESTART R session!

library(devtools)
install_github("twitteR", username="geoffjentry")
library(twitteR)

api_key <- "mwcOI7mNkPUhRnnit0Nu75VBO"

api_secret <- "BwyN7OvghbPSW9RDSaSzVu0aRhhH2bKRvQcUucUZQYyxbKSW2u"

access_token <- "2829195264-D8HgRXZCyUd193lC5ILEFsxgGdgIldvBP8zo64E"

access_token_secret <- "2829195264-D8HgRXZCyUd193lC5ILEFsxgGdgIldvBP8zo64E"

setup_twitter_oauth(api_key,api_secret,access_token,access_token_secret)

and i get this error 

Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

please can someone help me i reaaly need this problem solve pleasee

**Comment by flowsta** [comment]
same problem, do you know if it's fixed?

**Comment by technomudit** [comment]
SAme issue with httr 0.6.1 and twitteR_1.1.8

**Comment by geoffjentry** [comment]
My standard response to people struggling with their connection is to follow this example:
https://github.com/hadley/httr/blob/master/demo/oauth1-twitter.r

If you can't get that to work, contact Hadley. If you can, let me know - but to date I've not seen a case where one works and the other doesn't.

**Comment by technomudit** [comment]
Hey Jeff... Thanks for the reply. Looks like it was my firewall that was
blocking the authorisation. Thanks again.

**Comment by brindhanagarajan** [comment]
Check your firewall settings first. Make sure that R is added to the list of applications that can bypass the firewall.
Worked like a charm for me.

**Comment by MisbahAyoub** [comment]
Hi 
I have followed your script
https://github.com/hadley/httr/blob/master/demo/oauth1-twitter.r 
 successfully  but again 

setup_twitter_oauth(Consumer_key , Consumer_secret , access_token , access_token_secret)
[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
