### ISSUE TITLE
excludeReplies?

### ISSUE THREAD

**Issue by skyocean** [geoffjentry/twitteR#69]
Hi, I tried to get tweets excluding replies tweets and I used the following code, but it did not work.
userTimeline(user, n=20, maxID=NULL, sinceID=NULL, excludeReplies=T,includeRts=T,cainfo="cacert.pem")

However, the api 1.1 works well when I use twitter console, like this
https://api.twitter.com/1.1/statuses/user_timeline.json?trim_user=t&exclude_replies=t&include_rts=f&screen_name=...

**Comment by geoffjentry** [comment]
No reproducible example, nearly 2 years old. Closing.
