### ISSUE TITLE
How to retrieve multiple tweets from tweet_id using R

### ISSUE THREAD

**Issue by Ruviansh** [geoffjentry/twitteR#70]
I am using the twitteR package in R to extract tweets based on their ids. But I am unable to do this for multiple tweet ids without hitting either a rate limit or an error 404. This is because I am using the showStatus() - one tweet id at a time. I am looking for a function similar to getStatuses() - multiple tweet id/request

Is there an efficient way to perform this action. I suppose only 60 requests can be made in a 15 minute window using the outh.

So, how do I ensure :- 
1.Retrieve multiple tweet ids for single request thereafter repeating these requests. 
2.Rate limit is under check. 
3.Error handling for tweets not found.

P.S : This activity is not user based.

Thanks

**Comment by Ruviansh** [comment]
Thanks Geoff...It does.

**Comment by bs77** [comment]
I am curious why there isn't an function in your package corresponding to
get/statuses/lookup requests. Is it because that type of request requires a
different authentication type?

Thanks,
Ben

**Comment by geoffjentry** [comment]
Purely an oversight. I don't have much time to poke at twitteR these days so normally I only add things if someone asks for it or if they submit a pull request.

**Comment by geoffjentry** [comment]
Resolved and on CRAN now
