### ISSUE TITLE
can_accesss_other_account throws error when throttle exceeded

### ISSUE THREAD

**Issue by elbamos** [geoffjentry/twitteR#73]
This is the error:

**Comment by dataaa** [comment]
I also encounter this. Traceback:


12 can_access_other_account(user_id) 
11 ffBase("followers", user_id, n, ...) 
10 followers(.self$id, n, ...) 
9 unlist(followers(.self$id, n, ...)) 
8 getUser(x, retryOnRateLimit = 120)$getFollowerIDs() at twitterChamps.R#24
7 FUN(c("1122943080", "620855894", "576511985", "247491366", "1921398566", 
"44649091", "225159286", "2600540883", "287299456", "631940215", 
"2293443870", "37752270", "17919856", "240211954", "259941902", 
"76956151", "2582900435", "26239099", "19444467", "2403339895",  ... 
6 lapply(X = X, FUN = FUN, ...) 
5 sapply(retUsers, function(x) length(getUser(x, retryOnRateLimit = 120)$getFollowerIDs())) at twitterChamps.R#24
4 eval(expr, envir, enclos) 
3 eval(ei, envir) 
2 withVisible(eval(ei, envir)) 
1 source("~/Downloads/urbandatahackathon/twitterChamps.R")

**Comment by danielcarter** [comment]
I'm also running into this issue -- was there ever a solution? Traceback is below:

Error in can_access_other_account(user_id) : 
attempt to apply non-function 

8 can_access_other_account(user_id) 
7 ffBase("friends", user_id, n, ...) 
6 friends(.self$id, n, ...) 
5 unlist(friends(.self$id, n, ...)) 
4 .self$getFriendIDs(n, ...) 
3 origin$getFriends() 
2 FUN(X[[5L]], ...) 
1 lapply(twitter_users_batch_8, make_friends_list)

**Comment by Jeff-Winchell** [comment]
I also have this too. Its been a while since this bug was first reported. Is this codebase being abandoned?

**Comment by chris-malvern** [comment]
I got this while going through Twitter accounts for friend lists: protected accounts!
