### ISSUE TITLE
blocking for a minute?

### ISSUE THREAD

**Issue by vanstark88** [geoffjentry/twitteR#76]
Hi, I am running:
flu<-searchTwitter('flu',50000,lang="en",since='2013-01-01',until='2015-01-26')
[1] "Rate limited .... blocking for a minute and retrying up to 119 times ..."
[1] "Rate limited .... blocking for a minute and retrying up to 118 times ..."
[1] "Rate limited .... blocking for a minute and retrying up to 117 times ..."

Any idea what might cause this?

**Comment by geoffjentry** [comment]
You've been rate limited by Twitter, as the message says. 

https://dev.twitter.com/rest/public/rate-limiting

**Comment by raghav2** [comment]
I am getting the same message. My understanding of the rate limit is on "requests made to server". I didn't make as many as 60 or 180 or 450 requests in a given time window.. if anything i made like 5 requests a 24 hours window.. why am i getting this ?

Having said that, I am asking for a certain number of tweets e.g. searchTwitter(xx, n=9999, lang ="en") Could that cause the rate limit ??
