### ISSUE TITLE
t.co shortening isn't taken into account when posting 140 char tweets

### ISSUE THREAD

**Issue by lmmx** [geoffjentry/twitteR#80]
This package doesn’t even attempt to use URL length = 23 characters (max.), as described on the [t.co dev page](https://dev.twitter.com/overview/t.co), so valid tweets are `stop`ped in [statuses.R](https://github.com/geoffjentry/twitteR/blob/7193e44af0f711c8a8631c07269dcc1e41b2d08a/R/statuses.R#L156-L162)

An optional parameter to override this would be good (I've forked and simply removed the line, as I'm doing the character limit check upstream of calling updateStatus)

To summarise:

* `https://` links count for 23 characters
  * ...leaving 116 characters of text after an intervening space
* `http://` links count for 22 characters
  * ...leaving 117 characters of text after an intervening space
* These link character lengths "[will increase with time](https://dev.twitter.com/overview/t.co)" !

I'm working on [a function](https://github.com/lmmx/ScholarDaemon/blob/cc7aa13ac0589f16c995f80702d3e91dd86c62f7/ScholarDaemon.R#L32-L169) to make tweets composed simply of 1 piece of text (potentially truncated to fit) + 1 link &le; 140 char's, and I'm pretty certain all links will start in http / https, so can script for these possibilities.

If this is to be a really accurate twitter client then this prefix check probably won't suffice, and maybe an R package for handling URLs would be appropriate (using its code if not adding another dependency anyway).

Twitter itself seems to check for domain suffixes too somehow in its web interface - typing "google.com" is picked up as a URL for example.

**Comment by geoffjentry** [comment]
Hey there - in my defense, I'm pretty sure updateStatus predates link shortening but perhaps I'm just lazy :)

Because I rarely get time to handle the bits that are at the top of my priority list I'll be honest and say that I'm unlikely to be able to deal w/ this any time soon (but thanks for posting it, I'll *eventually* get to it!) so if you do end up putting together a good solution please submit a PR and I can fold it in.

**Comment by lmmx** [comment]
Haha no not at all, I was just making an observation and wanted to note it, for my own reference or anyone else already working on the package.

I take it `twitteR` users probably are more interested in read than write capabilities, so it's understandable.

When I tried to reconstruct the function that was being `stop`ped, some (possibly OOP?) part of the program was 'locked'. I'm not up to scratch on this level of R.

As a result it's not possible to just delete `if (nchar(text) > 140) { ... }` altogether and avoid the `stop`, so I uninstalled, reinstalled from source on a local edited copy with these lines removed, since the class definition of `twAPIInterface` called by/held in `twInterfaceObj` (...?) is "locked".

```r
# from twitteR/R/comm.R lines 106-108
https://github.com/geoffjentry/twitteR/blob/74c168a53b7a732e978ebe623311549861e63f05/R/comm.R#L106-L108

tint <- getRefClass('twAPIInterface')
tint$accessors(names(tint$fields()))
# errors out, see below
twInterfaceObj <- tint$new()

# mimicking/simplifying buildCommonArgs in twitteR/R/utils.R lines 37-50
# https://github.com/geoffjentry/twitteR/blob/dbef2224439f85812a28141dfe1783559991e858/R/utils.R#L37-L50

params <- list(status = 'text')
json = twInterfaceObj$doAPICall(endpoint,
                                 params=params, method='POST', ...)
return(buildStatus(json))

SendTweet <- function(final.tweet) {
   if (nchar(final.tweet) <= 140) {
      updateStatus(final.tweet) # easy route as even with a full length URL it's below 140
   } else {
      # preferably get the actual character limit by looking at the URL(s)
      # rather than just not checking character limit at all
   }
}
```

<pre>> tint$accessors(names(tint$fields()))
Error in tint$accessors(names(tint$fields())) : 
  the definition of class “twAPIInterface” in package ‘twitteR’ is locked so fields may not be modified</pre>

To keep things simple I'd probably just add a logical parameter, default off, like `bypass_char_limit = F` as an *or* condition (but better yet would be to pass in the updated character limit itself, subject to the same policy as the API we're communicating with).

**Comment by geoffjentry** [comment]
Yeah - when I originally put this package together it was just to demonstrate to a coworker that one could tweet from R but I quickly discovered that the actual mode of use is heavily in favor of reading, not writing. I'm pretty sure flaws in the writing oculd hide out for years without anyone knowing :)

**Comment by geoffjentry** [comment]
Long since closed due to submitted patch
