### ISSUE TITLE
Rate Limited

### ISSUE THREAD

**Issue by raghav2** [geoffjentry/twitteR#88]
I am getting the same message.

>[1] "Rate limited .... blocking for a minute and retrying up to 119 times ..."

 My understanding of the rate limit is on "requests made to server". I didn't make as many as 60 or 180 or 450 requests in a given time window.. if anything i made like 5 requests a 24 hours window.. why am i getting this ?

Having said that, I am asking for a certain number of tweets e.g. searchTwitter(xx, n=9999, lang ="en") Could that cause the rate limit ??

**Comment by geoffjentry** [comment]
Note that many of the functions in twitteR are making multiple calls to the Twitter API under the hood. You might have only made one R call but there might be hundreds of Twitter API calls being made.
