### ISSUE TITLE
Error in check_twitter_oauth( )

### ISSUE THREAD

**Issue by theRanalyst** [geoffjentry/twitteR#90]
I know this issue has come up before when Hadley has made changes to his httr package, but I wanted to bring it to your attention again as he just pushed version 1.0.0.9000 and it seems to be causing the same issue. The following works as a workaround in the meantime.
```
devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")
```
Just be sure to restart R after running the command.

**Comment by mobcdi** [comment]
Is that work around to be carried out during the install of twitteR or when executing any commands from the package? Also does it work if you install twitteR from cran?

**Comment by theRanalyst** [comment]
@mobcdi The work around should be introduced if and only if you're looking to work with the `twitteR` package. Otherwise, you should use the most up-to-date version of `httr`. Essentially, your initial workflow would look like this:

```
install.packages("twitteR")
library(twitteR)
library(devtools) #if not installed, do that obviously
devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org"
#A restart of R might be necessary if you previously had httr installed.
library(httr)
setup_twitter_oauth(consumerKey, consumerSecret, accessKey, accessSecret)
#some twitter functions
```

After this initial workflow, any time you launch R, you would just call `twitteR` and `httr` as usual, setup your oauth and run your analyses. As for the version of `twitteR`, I'm currently running 1.1.8, which I downloaded from CRAN.

**Comment by mobcdi** [comment]
I think you need to change the order you load the packages as twitteR depends on httr so will error if you try to load it before installing the version from archives

When I run (on 64bit windows using RStudio)
<code> devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")</code> I get the following
<code>Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/httr/httr_0.6.0.tar.gz
Error in loadNamespace(name) : there is no package called ‘httr’ </code>
Even though the tar.gz file is available at http://cran.us.r-project.org/src/contrib/Archive/httr/httr_0.6.0.tar.gz 

Any recommendations on how to solve it

**Comment by theRanalyst** [comment]
I already had `twitteR` installed - which is how I found out there was an issue with `setup_twitter_oauth` - when I installed the older version of `httr`, so the order shouldn't need to be changed, but if you'd like to install the older version of `httr` first, that obviously wouldn't throw a wrench in anything. 

As for the error you're getting, I would try to install a working version of `httr` first (aka `install.packages(httr)`) and then run install the older version. I'm not sure why you'd need to have a newer version installed first, but that's the scenario in which I got this to work on a 64-bit Windows machine.

**Comment by mobcdi** [comment]
installing the most recent version on cran worked, followed by restarting the session, then loading the twitter library and running through setup_twitter_oauth with valid keys and secrets. 

Thanks for the help,

**Comment by meewmiiuuw** [comment]
hi, i've been trying to run the command, and here are the following output :

> devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")
Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/httr/httr_0.6.0.tar.gz
Installing httr
"C:/PROGRA~1/R/R-32~1.0/bin/i386/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/meewmiiuw/AppData/Local/Temp/Rtmp2jAK24/devtools104c6237643f/httr"  \
  --library="C:/Program Files/R/R-3.2.0/library" --install-tests 

* installing *source* package 'httr' ...
** package 'httr' successfully unpacked and MD5 sums checked
** libs
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.0/share/make/winshlib.mk" SHLIB="httr.dll" OBJECTS="writer.o"' had status 127
ERROR: compilation failed for package 'httr'
* removing 'C:/Program Files/R/R-3.2.0/library/httr'
* restoring previous 'C:/Program Files/R/R-3.2.0/library/httr'
Error: Command failed (1)


i've been uninstall and then reinstall R but the problem is still the same in the part of "Error in check twitter_oauth() "

any help to fix this are appreciate.

**Comment by theRanalyst** [comment]
@meewmiiuuw This issue is probably more suited for @hadley as it deals specifically with `httr` and not the `twitteR` package, but I'll take a stab at it. Based on the fact that you're getting a compilation error when trying to build the package, I'm going to assume you're on a Windows machine and you don't have `RTools` installed. Trying issuing the `install.packages("RTools")` command and then running the above solution and see if that works. If you continue to have further issues, you should ask your question [here](http://www.stackoverflow.com).

**Comment by 278kunal** [comment]
I installed the httr version 0.6.0, i am still getting the same error  - 
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

My Session Info - 

R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] twitteR_1.1.8

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6     digest_0.6.8    R6_2.1.0        DBI_0.3.1       git2r_0.10.1   
 [6] magrittr_1.5    httr_0.6.0      stringi_0.5-5   curl_0.9.1      xml2_0.1.1     
[11] devtools_1.8.0  rjson_0.2.15    tools_3.2.1     stringr_1.0.0   bit64_0.9-4    
[16] bit_1.1-12      rversions_1.0.1 memoise_0.2.1

**Comment by theRanalyst** [comment]
I can't replicate your issue, so I don't know what's going on. Only thing I can think of is there are some typos in your keys and/or secrets.

**Comment by theRanalyst** [comment]
You may try looking through https://github.com/geoffjentry/twitteR/issues/74 as there seem to be some people there who can't get it to work either. May be a firewall issue or something with your system time.

**Comment by 278kunal** [comment]
Is the problem specifically with the httr_1.0.0 package ?  Because I installed twitteR_1.1.8 with httr_1.0.0 on two machines yesterday and same problem occured. Earlier with older version everything worked fine.

**Comment by theRanalyst** [comment]
Yes, it's a compatibility issue between twitteR and the most recent version of httr.

**Comment by 278kunal** [comment]
Thanks for the information.
Installed httr_0.6.0 , restarted RStudio , everything works like charm !
Thanks a lot !
You are a life saver ;)

**Comment by jrowen** [comment]
With `httr` v1.0 I think the `get_twitter_token_via_sign` function needs to be rewritten.  I've had luck with the approach below, which mimics much of the `httr` v0.6 logic.
```
get_twitter_token_via_sign = function(app, access_token, access_secret) {
  print("Using direct authentication")
  params <- list(as_header = TRUE)
  credentials <- list(oauth_token = access_token, 
                      oauth_token_secret = access_token_secret)
  twitter_token <- Token1.0$new(endpoint = NULL, params = params, 
                                app = app, credentials = credentials)
  
  if (is.null(twitter_token))
    stop("Invalid response for twitter_token")

  twitter_token
}
```

**Comment by mobcdi** [comment]
Could the same auth problem affect the streaming api package streamR?

**Comment by theRanalyst** [comment]
I may be wrong, but I believe the issue with the `streamR` package is that it needs a token with class "OAuth". However, `setup_twitter_oauth` returns a token with class "OAuth_1.0" (or something along those lines, I can't remember off the top of my head). You're supposed to be able to access the OAuth token by loading the .httr_oauth file that is created when you run `setup_twitter_oauth`, but I haven't been able to find that file. It gets added to my .gitignore file, but is no where to be seen in my working directory so I can't get past this part. Thus, I've never been able to get `streamR` to work.

**Comment by jrowen** [comment]
If you're interested, you can test out my suggestion here:
```
devtools::install_github("jrowen/twitteR", ref = "oauth_httr_1_0")
```

**Comment by neuwirthe** [comment]
I still get 
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'
after installing your modified version

**Comment by theRanalyst** [comment]
@neuwirthe Try restarting R and running the code again.

**Comment by neuwirthe** [comment]
I was doing it in RStudio and terminated the session.
Following your advice I completely closed RStudio and restarted, and then it worked.
Thank you!

**Comment by alfredo203** [comment]
@theRanalyst Thank you very much, I had struggled with the problem in Authentication with httr package.

The solution was to install httr older version (0.6.0): 

devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")

**Comment by geoffjentry** [comment]
Hi all - Thanks to @jrowen I believe this is resolved via PR #92 . Try installing via devtools.

**Comment by msstefb** [comment]
> devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")

Downloading package from url: http://cran.us.r-project.org/src/contrib/Archive/httr/httr_0.6.0.tar.gz

--how should I install the older version of httr?

**Comment by alfredo203** [comment]
@msstefb I would recommend installing from the command line, you should be working on R from terminal or GUI and run next code. Worked for me. Thanks to @jrowen

```
# Installing the devtools package
install.packages("devtools")

# Using devtools to install an older version
devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")
```

**Comment by theRanalyst** [comment]
@alfredo203 @msstefb Neither one of you should be using an old version of `httr` anymore. Install the latest version of `twitteR` from CRAN and also run `install.packages("base64enc")`. Once that's done, completely close out of R and RStudio and reopen it. It should work then.

**Comment by theRanalyst** [comment]
On second thought, use `devtools::install_github("geoffjentry/twitteR")` to ensure you get the latest fix.

**Comment by msstefb** [comment]
Here's my sessionInfo

> sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Philippines.1252  LC_CTYPE=English_Philippines.1252   
[3] LC_MONETARY=English_Philippines.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_Philippines.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] twitteR_1.1.8   httr_1.0.0      devtools_1.8.0  base64enc_0.1-2

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.6     digest_0.6.8    R6_2.1.0        DBI_0.3.1       git2r_0.10.1   
 [6] magrittr_1.5    stringi_0.5-5   curl_0.9.1      xml2_0.1.1      rjson_0.2.15   
[11] tools_3.2.1     stringr_1.0.0   bit64_0.9-5     bit_1.1-12      rversions_1.0.2
[16] memoise_0.2.1  

I am still encountering  

[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

**Comment by theRanalyst** [comment]
Did you shut down R completely and restart it?

**Comment by geoffjentry** [comment]
Hi all -

I just got 1.1.9 released which includes this change (and a few others in order to pass modern R CMD Check), try it off of CRAN and see what happens.

**Comment by NickMitchell7** [comment]
I had all the errors discussed in this thread and after trying the method explained last by @theRanalyst, using the setup_twitter_oauth() function worked first time. Thanks for your help @theRanalyst and for the great work @geoffjentry

**Comment by rohitgopidi** [comment]
installing the below package did the trick for me 
install.packages('base64enc')

**Comment by BobHarper1** [comment]
What worked for me (after trying alot of alternatives) httr v0.6.0 and twitteR 1.1.8 (@geoffjentry twitteR 1.1.9 does not seem to work with httr 0.6.0, at least on my version of R 3.2.2 x64 Windows)

**Comment by theRanalyst** [comment]
@BobHarper1 You shouldn't be using httr 0.6.0 anymore. The latest release of `twitteR` allows you to use the most up-to-date version of `httr`.

**Comment by geoffjentry** [comment]
In fact the latest version requires the newer httr

**Comment by BobHarper1** [comment]
Yes, but for whatever reason twitteR 1.1.9 results in the
`setup_twitter_oauth()` authentication error the subject of this issue
thread, for me anyway.

**Comment by theRanalyst** [comment]
Run `install.packages("base64enc")`, exit R completely, and try again.

**Comment by geoffjentry** [comment]
If you're installing twitteR with install.packages you shouldn't need to do that. It's a dependency of httr

**Comment by molx** [comment]
Installing `base64enc` solved it for me too. I guess it should be a dependency and installed along with `twitteR`?

**Comment by chapelon** [comment]
Hello everybody, 
this is quite a long discussion !
I could not read it entirely - as I solved it somehow quickly (but strangely) - but I'd like to add the following: we are now in December 2016 and there are still some trouble with the twitteR package (*), which I found strange... 
(*) by the way the latest version is now 1.1.9
I solved my issue with the following tip:
`devtools::install_version("httr", version="0.6.0", repos="http://cran.us.r-project.org")`
but I had to as well 
`devtools::install_version("twitteR", version="1.1.8", repos="http://cran.us.r-project.org")`
because it was not working with today's defautl 1.1.9 version !! (version which  was not working with the default version o httr)
Why do we still have uncompatibilty between the 2 packageswhen using latest version of each of them ?

**Comment by pssguy** [comment]
@chapelon Have you tried [rtweet](https://github.com/mkearney/rtweet)? I believe it is intended as a replacement for this package

**Comment by chapelon** [comment]
@pssguy thanks a lot, I'll try it. I confess that I discovered twitteR package last summer in a training and I was not aware of this "replacement".

**Comment by BobHarper1** [comment]
@pssguy Thanks for that, had not heard of rtweet will check it out of the library.

**Comment by geoffjentry** [comment]
@chapelon most likely it is because hadley is still developing `httr` and as @pssguy pointed out I haven't touched `twitteR` for quite a while. I have a lot of folks tell me that it still works for them but YMMV. There's a note at the start of the `README.md` and I made an announcement on the mailing list a while back.

**Comment by DGaffney** [comment]
Does anyone have a way of reliably avoiding this trap? I'm trying to get a fix set up for some students attempting to use https://github.com/vosonlab/SocialMediaLab, which still depends on twitteR. I've blasted my local R install and have tried building from 3.2.4-revised and 3.3.3, and in both cases I still hit this issue no matter what set of instructions I follow for getting these dependencies installed.

**Comment by neuwirthe** [comment]
When I played around some months ago,
I started using rtweet instead of twitteR.
It seemed to have an easier to use interface.
But I still think twitteR is a great packages.

**Comment by geoffjentry** [comment]
I recommend people to switch to rtweet, a while back he & I worked out a plan that twitteR is officially deprecated and I point people his way.

There's a chicken and egg problem in that I can't update the package to day that and get it on cran as I don't have time to update all the other things they'll want me to change

**Comment by DGaffney** [comment]
Is there a way by which I could copy your repo and install via github in devtools? This is really just looking for a solution that can be as hacky and temporary as my use case is excessively fleeting.

Devin

**Comment by geoffjentry** [comment]
@DGaffney not sure what you're asking to do. you mean you want to make some mods? you could fork and then point the devtools install to your own repo.

**Comment by DGaffney** [comment]
Correct - what exactly are the fixes I’d need to actually put into that temporary repo? I can’t seem to come up with a reliable set of install commands to get twitteR working right now on my end as it stands.

**Comment by geoffjentry** [comment]
@DGaffney Honestly I have no idea. Over the years I was very rarely able to reproduce issues like this, they typically amounted to mismatched dependency versions and things like that. Considering `twitteR` hasn't been updated in ages it's possible that modern versions of `httr` simply aren't compatible anymore. I haven't used it (or R) for a couple of years now so my memory of what to look at even is minimal.

**Comment by Mavericks334** [comment]
Hi

> library(twitteR)
> library(httr)
> library(devtools)
> consumer_key = "****"
> consumer_secret= "****"
> access_token= "****"
> access_secret = "****"
> setup_twitter_oauth(consumer_key,consumer_secret,access_token,access_secret)

I am getting this error 

"Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

If i only try 
setup_twitter_oauth(consumer_key,consumer_secret)

I am getting this error.

"Using browser based authentication"
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached.

How do i go about it. I am using R 3.4.0.

Regards,
Ren.

**Comment by richaagrawa** [comment]
hello everyone
please help me with this error i have tried all above solutiions but still getting this error 

setup_twitter_oauth(consumerKey,
                     consumerSecret,
                     accessToken,
                     accessTokenSecret)
   "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'

**Comment by ghost** [comment]
@richaagrawa This package is deprecated, and you should be using [rtweet](https://github.com/mkearney/rtweet/) instead.

**Comment by richaagrawa** [comment]
I tried using rtweet but that too didn't worked.
