### ISSUE TITLE
'reTweeted' is not set to TRUE for a tweet that is retweeted multiple times

### ISSUE THREAD

**Issue by VenkatArchitect** [geoffjentry/twitteR#94]
For a tweet which has been retweeted multiple times (note: this is the original tweet), the 'reTweeted' field is not set to TRUE.  It shows as FALSE always.

**Comment by geoffjentry** [comment]
That's not what that field means. See the Twitter API: https://dev.twitter.com/overview/api/tweets - https://dev.twitter.com/overview/api/tweets ... `retweeted` means that the authenticating user has retweeted it.

There's also `isRetweet` which will be `TRUE` if either `retweeted` is `TRUE` OR if the tweet itself is actually a retweet.
