### ISSUE TITLE
dmGet and dmSent don't deal with new DM longer format

### ISSUE THREAD

**Issue by yrochat** [geoffjentry/twitteR#99]
It is only since [very recently] (https://blog.twitter.com/2015/removing-the-140-character-limit-from-direct-messages) that Twitter has suppressed the 140 characters limit for direct messages. I don't know if that is too fresh and can be managed with the API (the non-official-Twitter mobile app that I use doesn't). dmGet and dmSent retrieve the messages truncated to ~140 characters.

**Comment by geoffjentry** [comment]
Hi, the `dmSend` function in twitteR will limit to 140 chars but `dmGet` is exactly what comes back from the API. I just checked the REST API specs and it still says to keep the text of a sent DM to 140 characters so it appears that it's still a limitation

**Comment by yrochat** [comment]
That's sad. Thank you for the answer!

**Comment by emillykkejensen** [comment]
This link should be interesting to follow: https://twittercommunity.com/t/removing-the-140-character-limit-from-direct-messages/41348
